
services:
  api:
    build: .
    ports:
      - "8080:8080"
    restart: always

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://api:8080/swagger.yaml
    depends_on:
      - api